# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d812d971d8052376f8c7baf07f638e90333e4028fd211565f983f34e028cc2e169915fbbac0ce11b9605b258e835204d162fb35138883e4dad9fe2fb82f61e2b

test:
  secret_key_base: 7b0c3f02edef71f4eefa0aa06191d4e66dc533f1a2463ea89e4abe7b5f7572115a4dfae4289f9aeea3eed56e1691d3766bf6db448403338357ea38fd3c37afa1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
